# SITE CONFIGURATION
baseurl: ""
url: "https://reactdevstation.github.io"

# THEME-SPECIFIC CONFIGURATION
title: "React Dev Station" # site's title
description: "All about React, JS & CSS" # used by search engines
avatar: assets/img/logo.png # Empty for no avatar in navbar
favicon: assets/favicon.ico # Icon displayed in the tab

# Header and footer text
header_text: <h1> Hello World  <h1> <p>Its a blog about the world of React. </p> # Change Blog header text
header_feature_image: assets/img/pexels/triangular.jpeg
footer_text: >
  Happy Coding <i class="fa fa-smile-o" aria-hidden="true"></i>


# Blog
excerpt: true # Or "truncate" (first 250 characters), "false" to disable
post_navigation: true
color_image: /assets/img/lineart.png # A bit transparent for color posts.

# Features
katex: true # Enable if using math markup
google_analytics: UA-160725381-1 # Tracking ID, e.g. "UA-000000-01"
disqus_shortname: https-reactdevstation-github-io # Your discus shortname for comments
layout_variables: # Open the "_sass > base" folder, and open "_variables.scss"
footer_icons: # In _data/social.yml
share_buttons: # In _data/social.yml
authors: rustyonrampage # In _data/authors.yml
language: english # In _data/language.yml

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# PORTFOLIO
collections:
  portfolio:
    output: true
    permalink: /:collection/:name

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-feed, jekyll-sitemap]
exclude:
  [
    ".jekyll-cache",
    "Gemfile",
    "Gemfile.lock",
    "type-on-strap.gemspec",
    "*.gem",
    ".idea",
    "vendor/*",
    "LICENSE",
    "README.md",
    "screenshot.png",
    "assets/package.json",
    "assets/node_modules",
    "assets/gulpfile.js",
  ]

# theme: type-on-strap                                  # if using the theme as a jekyll theme gem
remote_theme: sylhare/Type-on-Strap # If using as a remote_theme in github
